# Generated by Django 5.1.1 on 2024-09-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_model',
            name='subscription_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription_model',
            name='subscription_type',
            field=models.CharField(default='monthly', max_length=10),
        ),
    ]
