# Generated by Django 5.1.1 on 2024-09-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_subscription_model_subscription_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_model',
            name='subscription_end',
            field=models.DateTimeField(null=True),
        ),
    ]
